const opts = (list = [], label = 'name') => list.map((r) => ({ value: r.id, label: r[label] }));
const tierOpts = (tiers = []) => tiers.map((t) => ({ value: t.key, label: t.label }));
const tierLabel = (tiers = [], key) => tiers.find((t) => t.key === key)?.label ?? key;

export const DEPARTMENTS = {
  resource: 'departments',
  title: 'Departments',
  singular: 'Department',
  icon: 'building',
  description: 'Academic and non-academic departments. Each can have a head, image and description; they also populate the website menu.',
  titleKey: 'name',
  imageKey: 'image',
  fallbackIcon: 'building',
  activeKey: 'is_active',
  reorderable: true,
  reloadSite: true,
  needs: ['staff'],
  searchKeys: ['name', 'summary'],
  subtitle: (r, ctx) => {
    const head = ctx.staff?.find((s) => s.id === r.head_id);
    return head ? `Head: ${head.name}` : 'No head assigned';
  },
  badges: (r, ctx) => [{ label: `${ctx.staff?.filter((s) => s.department_id === r.id).length ?? 0} staff` }],
  defaults: () => ({ icon: 'journal-bookmark', is_active: 1 }),
  fields: [
    { key: 'name', label: 'Department name', required: true, col: 'col-md-8' },
    { key: 'icon', type: 'icon', label: 'Icon', col: 'col-md-4' },
    { key: 'head_id', type: 'select', numeric: true, label: 'Head of department', col: 'col-md-6', empty: '— None —', options: (ctx) => opts(ctx.staff), help: 'Add the person under Teachers & Staff first.' },
    { key: 'slug', label: 'Web address', col: 'col-md-6', help: 'Generated automatically from the name.', placeholder: 'auto' },
    { key: 'summary', label: 'Short summary (cards)', type: 'textarea', rows: 2 },
    { key: 'description', label: 'Full description (blank line = new paragraph)', type: 'textarea', rows: 6 },
    { key: 'image', type: 'image', label: 'Department image', col: 'col-md-6' },
    { key: 'is_active', type: 'switch', label: 'Visible on website', col: 'col-md-6' },
  ],
};

export const STAFF = {
  resource: 'staff',
  title: 'Teachers & Staff',
  singular: 'Staff member',
  icon: 'person-badge',
  description: 'Everyone from the principal to heads of department, teachers and support staff. “Reports to” builds the school structure chart.',
  titleKey: 'name',
  imageKey: 'photo',
  roundImage: true,
  activeKey: 'is_active',
  reorderable: true,
  needs: ['departments'],
  searchKeys: ['name', 'position', 'email'],
  subtitle: (r, ctx) => [r.position, ctx.departments?.find((d) => d.id === r.department_id)?.name].filter(Boolean).join(' · '),
  badges: (r, ctx) => [
    { label: tierLabel(ctx.tiers?.staff, r.tier) },
    r.featured && { label: 'Homepage', tone: 'accent' },
  ],
  filters: [
    { key: 'tier', label: 'Level', options: (ctx) => tierOpts(ctx.tiers?.staff) },
    { key: 'department_id', label: 'Department', options: (ctx) => opts(ctx.departments) },
  ],
  defaults: (ctx) => ({ tier: ctx.tiers?.staff?.at(-2)?.key ?? 'teacher', is_active: 1, featured: 0 }),
  fields: [
    { key: 'photo', type: 'image', label: 'Photo', col: 'col-md-4', aspect: 'aspect-[4/5]' },
    { key: '_', type: 'heading', label: 'Profile', col: 'col-md-8' },
    { key: 'name', label: 'Full name (with title, e.g. Mr. / Dr.)', required: true, col: 'col-md-8' },
    { key: 'position', label: 'Position / role', col: 'col-md-8', placeholder: 'e.g. Head of Sciences' },
    { key: 'tier', type: 'select', label: 'Hierarchy level', col: 'col-md-4', empty: false, options: (ctx) => tierOpts(ctx.tiers?.staff) },
    { key: 'department_id', type: 'select', numeric: true, label: 'Department', col: 'col-md-4', empty: '— None —', options: (ctx) => opts(ctx.departments) },
    { key: 'parent_id', type: 'select', numeric: true, label: 'Reports to', col: 'col-md-4', empty: '— Top of hierarchy —', options: (ctx, row) => opts(ctx.staff?.filter((s) => s.id !== row?.id)) },
    { key: 'qualifications', label: 'Qualifications', col: 'col-md-12', placeholder: 'e.g. B.Ed Mathematics, M.Ed Leadership' },
    { key: 'email', type: 'email', label: 'Email (optional, shown publicly)', col: 'col-md-6' },
    { key: 'phone', label: 'Phone (optional, shown publicly)', col: 'col-md-6' },
    { key: 'bio', label: 'Short biography', type: 'textarea', rows: 4 },
    { key: 'featured', type: 'switch', label: 'Feature on homepage', col: 'col-md-6', help: 'Shown in the “Meet Our Leadership” section' },
    { key: 'is_active', type: 'switch', label: 'Visible on website', col: 'col-md-6' },
  ],
};

export const PREFECTS = {
  resource: 'prefects',
  title: 'Prefects',
  singular: 'Prefect',
  icon: 'stars',
  description: 'The prefects body — from the head boy and head girl down. Levels set to “show photos” display selfies; others appear by name.',
  titleKey: 'name',
  imageKey: 'photo',
  roundImage: true,
  activeKey: 'is_active',
  reorderable: true,
  searchKeys: ['name', 'position', 'class_name'],
  subtitle: (r) => [r.position, r.class_name].filter(Boolean).join(' · '),
  badges: (r, ctx) => [{ label: tierLabel(ctx.tiers?.prefects, r.tier) }, r.show_photo && { label: 'Photo', tone: 'accent' }],
  filters: [{ key: 'tier', label: 'Level', options: (ctx) => tierOpts(ctx.tiers?.prefects) }],
  defaults: (ctx) => ({ tier: ctx.tiers?.prefects?.at(-1)?.key ?? 'prefect', is_active: 1, show_photo: 0 }),
  fields: [
    { key: 'photo', type: 'image', label: 'Photo / selfie', col: 'col-md-4', aspect: 'aspect-[4/5]' },
    { key: '_', type: 'heading', label: 'Details', col: 'col-md-8' },
    { key: 'name', label: 'Full name', required: true, col: 'col-md-8' },
    { key: 'position', label: 'Position', col: 'col-md-8', placeholder: 'e.g. Head Girl, Games Captain' },
    { key: 'tier', type: 'select', label: 'Level', col: 'col-md-4', empty: false, options: (ctx) => tierOpts(ctx.tiers?.prefects) },
    { key: 'class_name', label: 'Class / form', col: 'col-md-4', placeholder: 'Form 4 East' },
    { key: 'house', label: 'House / dorm', col: 'col-md-4' },
    { key: 'quote', label: 'Quote or message', type: 'textarea', rows: 2 },
    { key: 'show_photo', type: 'switch', label: 'Always show photo', col: 'col-md-6', help: 'Even if the level shows names only' },
    { key: 'is_active', type: 'switch', label: 'Visible on website', col: 'col-md-6' },
  ],
};

export const NEWS = {
  resource: 'news',
  title: 'News & Events',
  singular: 'Post',
  icon: 'newspaper',
  description: 'Publish school news and upcoming events. Events with a future date appear in the homepage calendar.',
  titleKey: 'title',
  imageKey: 'image',
  fallbackIcon: 'newspaper',
  activeKey: 'is_published',
  searchKeys: ['title', 'excerpt'],
  subtitle: (r) => (r.category === 'event' && r.event_date ? `Event on ${r.event_date}${r.location ? ` · ${r.location}` : ''}` : `Published ${String(r.created_at).slice(0, 10)}`),
  badges: (r) => [{ label: r.category === 'event' ? 'Event' : 'News', tone: r.category === 'event' ? 'accent' : undefined }, !r.is_published && { label: 'Draft', tone: 'muted' }],
  filters: [{ key: 'category', label: 'Type', options: () => [{ value: 'news', label: 'News' }, { value: 'event', label: 'Events' }] }],
  defaults: () => ({ category: 'news', is_published: 1, created_at: new Date().toISOString().slice(0, 19).replace('T', ' ') }),
  beforeSave: (row) => ({ ...row, created_at: row.created_at && row.created_at.length === 10 ? `${row.created_at} 08:00:00` : row.created_at }),
  fields: [
    { key: 'title', label: 'Title', required: true, col: 'col-md-8' },
    { key: 'category', type: 'select', label: 'Type', col: 'col-md-4', empty: false, options: [{ value: 'news', label: 'News article' }, { value: 'event', label: 'Event' }] },
    { key: 'event_date', type: 'date', label: 'Event date', col: 'col-md-4', showIf: (v) => v.category === 'event' },
    { key: 'location', label: 'Venue', col: 'col-md-8', showIf: (v) => v.category === 'event' },
    { key: 'image', type: 'image', label: 'Cover image', col: 'col-md-5' },
    { key: 'excerpt', label: 'Summary (shown on cards)', type: 'textarea', rows: 5, col: 'col-md-7' },
    { key: 'body', label: 'Full article (blank line = new paragraph)', type: 'textarea', rows: 10 },
    { key: 'created_at', type: 'date', label: 'Publish date', col: 'col-md-6' },
    { key: 'is_published', type: 'switch', label: 'Published (uncheck to keep as draft)', col: 'col-md-6' },
  ],
};

export const USERS = {
  resource: 'users',
  title: 'Users',
  singular: 'User',
  icon: 'people',
  description: 'People who can sign in through the portal. Administrators manage everything; editors manage content but not branding or users.',
  titleKey: 'name',
  imageKey: null,
  activeKey: 'is_active',
  searchKeys: ['name', 'email'],
  modalSize: undefined,
  subtitle: (r) => r.email,
  badges: (r) => [{ label: r.role === 'admin' ? 'Administrator' : 'Editor', tone: r.role === 'admin' ? 'accent' : undefined }],
  defaults: () => ({ role: 'editor', is_active: 1 }),
  fields: [
    { key: 'name', label: 'Full name', required: true },
    { key: 'email', type: 'email', label: 'Email (used to sign in)', required: true },
    { key: 'role', type: 'select', label: 'Role', empty: false, col: 'col-md-6', options: [{ value: 'editor', label: 'Editor' }, { value: 'admin', label: 'Administrator' }] },
    { key: 'is_active', type: 'switch', label: 'Account active', col: 'col-md-6' },
    { key: 'password', type: 'password', label: 'Password', help: 'At least 8 characters. When editing, leave blank to keep the current password.' },
  ],
};
